"""Operator absence system runtime types.

Pydantic models for operator interaction tracking, absence escalation,
restriction enforcement, and return workflow.

All operator absence logic is deterministic (Tier D).
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# --- Enums ---


class InteractionType(str, Enum):
    """Types of operator interactions with the system."""

    LOGIN = "login"
    DASHBOARD_VIEW = "dashboard_view"
    MANUAL_TRIGGER = "manual_trigger"
    CONFIG_CHANGE = "config_change"
    ALERT_ACKNOWLEDGMENT = "alert_acknowledgment"


class AbsenceLevel(int, Enum):
    """Operator absence escalation levels.

    0: Normal (0-48hr)
    1: Absent Level 1 (48-72hr) — no new positions, increased review, alerts
    2: Absent Level 2 (72-96hr) — 25% size reduction, escalated alert
    3: Absent Level 3 (96-120hr) — additional 25% reduction, wind-down prep
    4: Graceful Wind-Down (120hr+) — close targets → break-even → scheduled
    """

    NORMAL = 0
    ABSENT_LEVEL_1 = 1
    ABSENT_LEVEL_2 = 2
    ABSENT_LEVEL_3 = 3
    GRACEFUL_WINDDOWN = 4


ABSENCE_LEVEL_NAMES: dict[AbsenceLevel, str] = {
    AbsenceLevel.NORMAL: "normal",
    AbsenceLevel.ABSENT_LEVEL_1: "absent_level_1",
    AbsenceLevel.ABSENT_LEVEL_2: "absent_level_2",
    AbsenceLevel.ABSENT_LEVEL_3: "absent_level_3",
    AbsenceLevel.GRACEFUL_WINDDOWN: "graceful_winddown",
}


class AbsenceAction(str, Enum):
    """Actions that the absence system is allowed to take."""

    # MAY do
    MAINTAIN_POSITIONS = "maintain_positions"
    REDUCE_POSITIONS = "reduce_positions"
    INCREASE_REVIEW_FREQUENCY = "increase_review_frequency"
    CLOSE_AT_TARGETS = "close_at_targets"
    CLOSE_AT_EXPIRY = "close_at_expiry"
    EXECUTE_RISK_FORCED_REDUCTIONS = "execute_risk_forced_reductions"
    SEND_ALERTS = "send_alerts"


class AbsenceRestriction(str, Enum):
    """Restrictions enforced during operator absence."""

    # MAY NEVER do
    NO_NEW_POSITIONS = "no_new_positions"
    NO_SIZE_INCREASES = "no_size_increases"
    NO_PARAMETER_CHANGES = "no_parameter_changes"
    NO_GOVERNOR_OVERRIDE = "no_governor_override"
    NO_DELAY_LEVEL_D = "no_delay_level_d"


class AbsenceAlertType(str, Enum):
    """Absence-specific alert types."""

    ABSENCE_MODE_ACTIVATED = "ABSENCE_MODE_ACTIVATED"
    ABSENCE_ESCALATED = "ABSENCE_ESCALATED"
    ABSENCE_SIZE_REDUCTION = "ABSENCE_SIZE_REDUCTION"
    ABSENCE_WINDDOWN_STARTED = "ABSENCE_WINDDOWN_STARTED"
    ABSENCE_OPERATOR_RETURNED = "ABSENCE_OPERATOR_RETURNED"
    ABSENCE_ACTION_TAKEN = "ABSENCE_ACTION_TAKEN"


# --- Interaction Tracking ---


class OperatorInteraction(BaseModel):
    """Record of an operator interaction."""

    interaction_type: InteractionType
    details: dict[str, Any] = Field(default_factory=dict)
    interacted_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


# --- Absence State ---


class AbsenceState(BaseModel):
    """Current operator absence state.

    Computed from the last interaction timestamp and current time.
    """

    absence_level: AbsenceLevel = AbsenceLevel.NORMAL
    absence_level_name: str = "normal"
    hours_since_last_interaction: float = 0.0
    last_interaction_at: datetime | None = None
    last_interaction_type: InteractionType | None = None

    # Cumulative reductions applied
    total_size_reduction_pct: float = 0.0

    # Restrictions in effect
    restrictions: list[AbsenceRestriction] = Field(default_factory=list)
    allowed_actions: list[AbsenceAction] = Field(default_factory=list)

    # Wind-down state
    winddown_active: bool = False
    winddown_started_at: datetime | None = None
    winddown_target_zero_at: datetime | None = None  # goal: zero in 72hr

    computed_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class AbsenceAlert(BaseModel):
    """Alert generated by the absence manager."""

    alert_type: AbsenceAlertType
    absence_level: AbsenceLevel
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    channels: list[str] = Field(default_factory=list)  # telegram, email, etc.
    generated_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class AbsenceActionRecord(BaseModel):
    """Record of an autonomous action taken during absence."""

    action: AbsenceAction
    absence_level: AbsenceLevel
    description: str
    positions_affected: list[str] = Field(default_factory=list)
    size_reduction_pct: float | None = None
    performed_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


# --- Return Workflow ---


class OperatorReturnSummary(BaseModel):
    """Summary presented to operator on return.

    Explicit acknowledgment required before normal operation resumes.
    """

    absence_duration_hours: float
    peak_absence_level: AbsenceLevel
    peak_absence_level_name: str

    # Actions taken during absence
    actions_taken: list[AbsenceActionRecord] = Field(default_factory=list)
    positions_reduced: list[str] = Field(default_factory=list)
    positions_closed: list[str] = Field(default_factory=list)
    alerts_sent: int = 0
    total_size_reduction_pct: float = 0.0

    # Important: reduced positions NOT automatically re-entered
    note: str = (
        "Reduced positions will NOT be automatically re-entered. "
        "New investigation cycles are required."
    )

    generated_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))

    # Must be acknowledged
    acknowledged: bool = False
    acknowledged_at: datetime | None = None
