"""Strategy viability system runtime types.

Pydantic models for viability checkpoints, budget-triggered reviews,
and deterministic threshold comparison.

All viability determination is by deterministic threshold comparison (Tier D).
Tier C summary writers may describe results for human readability.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# --- Enums ---


class ViabilityCheckpointType(str, Enum):
    """Types of viability checkpoints."""

    WEEK_4 = "week_4"        # Preliminary — insufficient data likely
    WEEK_8 = "week_8"        # Intermediate — compare if 20+ resolved
    WEEK_12 = "week_12"      # Decision — 50+ resolved → verdict
    BUDGET_50 = "budget_50"
    BUDGET_75 = "budget_75"
    BUDGET_100 = "budget_100"


class ViabilityStatus(str, Enum):
    """Viability determination status."""

    INSUFFICIENT_DATA = "insufficient_data"
    VIABLE = "viable"
    CONCERN = "concern"        # VIABILITY_CONCERN — system may be worse
    WARNING = "warning"        # VIABILITY_WARNING — operator must acknowledge


class ViabilityAlertType(str, Enum):
    """Viability-specific alert types for notification integration."""

    VIABILITY_CONCERN = "VIABILITY_CONCERN"
    VIABILITY_WARNING = "VIABILITY_WARNING"
    VIABILITY_CHECKPOINT = "VIABILITY_CHECKPOINT"
    BUDGET_THRESHOLD = "BUDGET_THRESHOLD"


# --- Checkpoint Input ---


class ViabilityMetrics(BaseModel):
    """Metrics used for viability determination.

    All computed deterministically (Tier D).
    """

    resolved_forecasts: int = 0

    # Brier scores
    system_brier: float | None = None
    market_brier: float | None = None
    base_rate_brier: float | None = None
    system_advantage: float | None = None  # market_brier - system_brier

    # PnL
    hypothetical_pnl: float | None = None

    # Cost metrics
    cost_of_selectivity: float | None = None
    total_inference_cost_usd: float | None = None

    # Accumulation
    accumulation_rate_per_week: float | None = None
    projected_50_resolved_date: datetime | None = None

    # Budget
    lifetime_budget_consumed_pct: float = 0.0
    daily_budget_remaining_pct: float = 1.0

    computed_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class ViabilityCheckpointInput(BaseModel):
    """Input for a viability checkpoint evaluation."""

    checkpoint_type: ViabilityCheckpointType
    system_week_number: int
    metrics: ViabilityMetrics
    operator_mode: str = "paper"


# --- Checkpoint Results ---


class ViabilityAlert(BaseModel):
    """Alert generated by the viability system."""

    alert_type: ViabilityAlertType
    checkpoint_type: ViabilityCheckpointType
    status: ViabilityStatus
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    requires_acknowledgment: bool = False
    generated_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class ViabilityCheckpointResult(BaseModel):
    """Result of a viability checkpoint evaluation.

    Includes the deterministic determination, the metrics snapshot,
    and any generated alerts.
    """

    checkpoint_type: ViabilityCheckpointType
    system_week_number: int

    # Determination (by deterministic threshold comparison)
    status: ViabilityStatus = ViabilityStatus.INSUFFICIENT_DATA
    status_note: str = ""

    # Metrics snapshot
    metrics: ViabilityMetrics = Field(default_factory=ViabilityMetrics)

    # Operator acknowledgment
    requires_acknowledgment: bool = False
    acknowledged: bool = False
    acknowledged_at: datetime | None = None

    # Alerts
    alerts: list[ViabilityAlert] = Field(default_factory=list)

    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


# --- Lifetime Budget ---


class LifetimeBudgetState(BaseModel):
    """Current lifetime experiment budget state.

    Continuous tracking with alerts at 50%, 75%, 100%.
    Level D operations never blocked.
    """

    total_budget_usd: float
    consumed_usd: float
    remaining_usd: float
    consumed_pct: float

    alert_50_triggered: bool = False
    alert_75_triggered: bool = False
    alert_100_triggered: bool = False

    investigations_paused: bool = False  # True at 100%(Level D never blocked)

    recorded_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))

    @property
    def is_exhausted(self) -> bool:
        return self.consumed_pct >= 1.0
