"""Bias detection system runtime types.

Pydantic models for the five statistical bias checks, pattern tracking,
audit report generation, and alert classification.

All bias detection is statistical (Tier D). LLM involvement is limited
to a Tier C summary writer that describes what statistics show — the LLM
does NOT detect biases or interpret whether they are problematic.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# --- Enums ---


class BiasPatternType(str, Enum):
    """Types of bias patterns the detector checks for."""

    DIRECTIONAL = "directional"
    CONFIDENCE_CLUSTERING = "confidence_clustering"
    ANCHORING = "anchoring"
    NARRATIVE_OVERWEIGHTING = "narrative_overweighting"
    BASE_RATE_NEGLECT = "base_rate_neglect"


class BiasAlertLevel(str, Enum):
    """Alert level for bias pattern tracking."""

    DETECTED = "detected"          # new pattern
    PERSISTENT = "persistent"      # 3+ consecutive weeks
    RESOLVED = "resolved"          # previously persistent pattern, now gone


class BiasAlertType(str, Enum):
    """Bias-specific alert types for notification integration."""

    BIAS_PATTERN_DETECTED = "BIAS_PATTERN_DETECTED"
    BIAS_PATTERN_PERSISTENT = "BIAS_PATTERN_PERSISTENT"
    BIAS_PATTERN_RESOLVED = "BIAS_PATTERN_RESOLVED"


# --- Input Data ---


class ForecastDataPoint(BaseModel):
    """A single forecast data point for bias analysis.

    Represents one resolved forecast with all fields needed for
    the five statistical checks.
    """

    forecast_id: str
    market_id: str
    category: str

    system_probability: float
    market_implied_probability: float
    base_rate_probability: float | None = None

    resolution_outcome: float  # 1.0 = Yes, 0.0 = No
    evidence_quality_score: float | None = None
    forecast_accuracy: float | None = None  # |system_prob - outcome|

    forecast_at: datetime
    resolved_at: datetime


class BiasDetectionInput(BaseModel):
    """Input to the bias detection processor for a weekly audit.

    Requires resolved forecasts over a lookback window (typically 4+ weeks).
    """

    forecasts: list[ForecastDataPoint] = Field(default_factory=list)
    period_start: datetime
    period_end: datetime

    # Previous patterns for persistence tracking
    previous_patterns: dict[str, int] = Field(
        default_factory=dict
    )  # pattern_type -> consecutive_weeks


# --- Check Results ---


class DirectionalBiasResult(BaseModel):
    """Result of directional bias check.

    Arithmetic mean comparison of system vs. market probability.
    Flag if persistent > 5pp skew over 3+ weeks.
    """

    detected: bool = False
    mean_system_probability: float | None = None
    mean_market_probability: float | None = None
    skew_pp: float | None = None  # percentage points
    sample_size: int = 0
    direction: str | None = None  # "bullish" or "bearish"


class ConfidenceClusteringResult(BaseModel):
    """Result of confidence clustering check.

    Histogram computation — flag if > 50% of forecasts within a 20pp band.
    """

    detected: bool = False
    peak_band_start: float | None = None
    peak_band_end: float | None = None
    pct_in_peak_band: float | None = None  # 0-1
    band_width_pp: float = 20.0
    sample_size: int = 0


class AnchoringResult(BaseModel):
    """Result of anchoring bias check.

    Mean absolute difference computation between system estimates
    and market prices. Flag if avg absolute difference consistently < 3pp.
    """

    detected: bool = False
    mean_abs_diff_pp: float | None = None  # percentage points
    threshold_pp: float = 3.0
    sample_size: int = 0


class NarrativeOverweightingResult(BaseModel):
    """Result of narrative coherence over-weighting check.

    Correlation analysis between evidence quality scores and forecast
    accuracy — checks if high-narrative-quality forecasts are less
    accurate than weak-narrative ones.
    """

    detected: bool = False
    correlation: float | None = None  # evidence_quality vs accuracy
    high_quality_accuracy: float | None = None
    low_quality_accuracy: float | None = None
    sample_size: int = 0


class BaseRateNeglectResult(BaseModel):
    """Result of base-rate neglect check.

    Statistical comparison of system estimates vs. base rates.
    Check if deviations are systematically directional.
    """

    detected: bool = False
    mean_deviation: float | None = None  # system - base_rate
    deviation_direction: str | None = None  # "above" or "below"
    systematically_directional: bool = False
    sample_size: int = 0


# --- Aggregated Results ---


class BiasPatternAlert(BaseModel):
    """Alert generated by the bias detection system."""

    alert_type: BiasAlertType
    pattern_type: BiasPatternType
    consecutive_weeks: int
    details: dict[str, Any] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class BiasAuditResult(BaseModel):
    """Complete result of a weekly bias audit.

    Contains all five statistical check results, pattern tracking,
    and any generated alerts.
    """

    period_start: datetime
    period_end: datetime
    sample_size: int = 0

    # Five statistical checks
    directional: DirectionalBiasResult = Field(
        default_factory=DirectionalBiasResult
    )
    confidence_clustering: ConfidenceClusteringResult = Field(
        default_factory=ConfidenceClusteringResult
    )
    anchoring: AnchoringResult = Field(default_factory=AnchoringResult)
    narrative_overweighting: NarrativeOverweightingResult = Field(
        default_factory=NarrativeOverweightingResult
    )
    base_rate_neglect: BaseRateNeglectResult = Field(
        default_factory=BaseRateNeglectResult
    )

    # Aggregate
    any_bias_detected: bool = False
    detected_patterns: list[BiasPatternType] = Field(default_factory=list)

    # Pattern persistence tracking
    pattern_weeks: dict[str, int] = Field(
        default_factory=dict
    )  # pattern_type -> current consecutive weeks

    # Alerts generated
    alerts: list[BiasPatternAlert] = Field(default_factory=list)

    # Summary (to be filled by Tier C writer)
    summary_text: str | None = None

    audited_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))
